ktor:
  application:
    modules:
      - webcrawler.ApplicationKt.module
  deployment:
    port: 10000

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
  topic:
    url-discovery: fru1tworld-webcrawling-url-discovery-v1

url-discovery:
  default-max-depth: 10
