ktor:
  application:
    modules:
      - htmldownloader.ApplicationKt.module
  deployment:
    port: 10002

database:
  driver: org.h2.Driver
  url: ${DATABASE_URL:-jdbc:h2:mem:webcrawler;DB_CLOSE_DELAY=-1}
  user: ${DATABASE_USER:-sa}
  password: ${DATABASE_PASSWORD:-}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
  group-id: html-downloader-group
  topic:
    url-discovery: fru1tworld-webcrawling-url-discovery-v1
